GET http://localhost:8085/api/public

###
POST http://localhost:8085/api/register
content-type: application/json

{
    "email": "email@email.com",
    "password": "1234",
    "phone":"208",
    "address":"thimi",
    "roles":["2"],
    "name":"Suresh"
}

###
POST http://localhost:8085/authenticate
Content-Type: application/json

{
    "username":"email@email.com",
    "password":"1234"
}

###
GET http://localhost:8085/api/listall

### 
GET http://localhost:8085/api/load
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbWFpbEBlbWFpbC5jb20iLCJleHAiOjE1NzI4NDUzNDMsImlhdCI6MTU3MjgyNzM0M30.iVvLE7sV9aYiDPKv595RibwQwkPFSapZwWcoH9tkGsUbsCQVAAmtE-8yJqhxDrtvi8r1gTxH88NGz1gS4KGQTQ