version: '3'

services:
  angular:
    container_name: client_start
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - "/app/node_modules"
      - ".:/app"